# Generated by Django 5.1.6 on 2025-05-07 16:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('idc', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('en_attente', 'En attente')], default='actif', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('idsec', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('fichier', models.FileField(blank=True, null=True, upload_to='section_fichiers/')),
                ('cache', models.BooleanField(default=False)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.cours')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('idu', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('motdepasse', models.CharField(max_length=100)),
                ('dateinscrit', models.DateField(auto_now_add=True)),
                ('specialisation', models.TextField(blank=True, null=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('niveau', models.CharField(blank=True, max_length=100, null=True)),
                ('specialite', models.CharField(blank=True, choices=[('info', 'Informatique'), ('med', 'Médecine'), ('ing', 'Ingénierie')], max_length=50, null=True)),
                ('type', models.CharField(choices=[('etudiant', 'Étudiant'), ('enseignant', 'Enseignant'), ('admin', 'Administrateur')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Travail',
            fields=[
                ('idT', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('typeT', models.CharField(choices=[('tp', 'Travail Pratique'), ('td', 'Travail Dirigé'), ('projet', 'Projet'), ('devoir', 'Devoir')], max_length=50)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='travaux/')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_limite', models.DateTimeField()),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('archive', 'Archivé')], default='actif', max_length=20)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travaux', to='core.cours')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Soumission',
            fields=[
                ('ids', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fichier', models.FileField(upload_to='soumissions/')),
                ('date_soumission', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('etat', models.CharField(choices=[('soumis', 'Soumis'), ('en_retard', 'En retard'), ('corrige', 'Corrigé'), ('note', 'Noté')], default='soumis', max_length=20)),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('travail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soumissions', to='core.travail')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soumissions', to='core.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('idp', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('methode', models.CharField(choices=[('cb', 'Carte Bancaire'), ('esp', 'Espèces'), ('virm', 'Virement')], max_length=50)),
                ('statutP', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='core.utilisateur')),
            ],
        ),
        migrations.AddField(
            model_name='cours',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='core.utilisateur'),
        ),
    ]
