# Generated by Django 5.1.6 on 2025-05-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='cours_inscrits',
            field=models.ManyToManyField(blank=True, related_name='etudiants_inscrits', to='core.cours'),
        ),
    ]
