# Generated by Django 5.1.6 on 2025-05-07 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_utilisateur_cours_inscrits'),
    ]

    operations = [
        migrations.AddField(
            model_name='soumission',
            name='valide',
            field=models.BooleanField(default=False, verbose_name="Validé par l'étudiant"),
        ),
        migrations.CreateModel(
            name='SectionVue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vue', models.DateTimeField(auto_now_add=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.utilisateur')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.section')),
            ],
        ),
    ]
