# Generated by Django 5.1.6 on 2025-05-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_soumission_valide_sectionvue'),
    ]

    operations = [
        migrations.AddField(
            model_name='travail',
            name='fichier_soumis',
            field=models.BooleanField(default=False),
        ),
    ]
