# Generated by Django 5.1.6 on 2025-05-07 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_travail_fichier_soumis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travail',
            name='fichier_soumis',
        ),
        migrations.AddField(
            model_name='soumission',
            name='fichier_soumis',
            field=models.BooleanField(default=False),
        ),
    ]
